version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: legal_compliance_mysql
    environment:
      MYSQL_ROOT_PASSWORD: Qwer.com123
      MYSQL_DATABASE: legal_compliance
      MYSQL_USER: root
      MYSQL_PASSWORD: Qwer.com123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped

volumes:
  mysql_data: 